language: ruby

env:
  global:
    JEKYLL_ENV: production

install:
  - bundle install

script:
  - bundle exec jekyll build -d _build

deploy:
  local-dir: _build
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
